### ISSUE TITLE
Include TextSecure

### ISSUE THREAD

**Issue by polyzen** [guardianproject/fdroid-repo#2]
Please include TextSecure

**Comment by eighthave** [comment]
TextSecure is not a Guardian Project app, you should file TextSecure requests on their issue tracker.  We only include Guardian Project apps in our repo.

**Comment by polyzen** [comment]
Sorry for the misunderstanding. Thank you

**Comment by eighthave** [comment]
no problem, good luck with TextSecure. I'd love to see them put their app into FDroid, so the more requests to them, the better.
